import './globals.css'
import { Montserrat } from 'next/font/google';
 
const montserrat = Montserrat({
  weight: ['500','700'],
  style: 'normal',
  preload: false,
})

export const metadata = {
  title: 'Joaquin De Luca',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({children}: {children: React.ReactNode}) {
 return (
    <html lang="en" className={montserrat.className}>
      <body>{children}</body>
    </html>
  )
}
